[build]
  publish = "dist"
  command = "npm run build"
  node_version = "18"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"